name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm i

      - name: Install vsce
        run: npm i -g vsce

      - name: Package
        run: vsce package -o started-dev.vsix
        env:
          ENVIRONMENT: Development

      - name: Package
        run: vsce package -o started-prod.vsix

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            started-dev.vsix
            started-prod.vsix